### ISSUE TITLE
Image uploader

### ISSUE THREAD

**Issue by komagata** [lokka/lokka#15]

**Comment by morygonzalez** [comment]
6 年前の Issue に対して失礼します…。 Amazon S3 にしかアップロードできませんが作ってみました。

![file-upload-demo](https://cloud.githubusercontent.com/assets/106567/22007513/89f2a04e-dcb6-11e6-9913-d044e034d071.gif)

**Comment by komagata** [comment]
@morygonzalez おお、いいですね！

**Comment by morygonzalez** [comment]
とりあえずのものはできたのでこの Issue は閉じていい気がします。
