### ISSUE TITLE
Lokka Plugin を集めたリポジトリを作りたい

### ISSUE THREAD

**Issue by morygonzalez** [lokka/lokka#228]
Lokka プラグインを集めたリポジトリがあったら便利ではないかと思ったのですがいかがでしょうか。 lokka/lokka-plugins とか？

**Comment by komagata** [comment]
@morygonzalez 確かにいいですね > lokka-plugins

**Comment by morygonzalez** [comment]
作ってみました〜。あとで自作の Plugin をいくつか追加します〜

https://github.com/lokka/lokka-plugins

**Comment by komagata** [comment]
おお、ありがとうございます！！
