### ISSUE TITLE
Plain HTML editor is broken

### ISSUE THREAD

**Issue by morygonzalez** [lokka/lokka#233]
### Problem

[jwysiwyg](https://github.com/jwysiwyg/jwysiwyg)'s plain HTML text editor is broken. This may happen on Chrome and Webkit. Originally [this was supposed to be a bug](https://github.com/jwysiwyg/jwysiwyg/issues/364) but it has never been solved and won't be.

### Options

1. Replace jwysiwyg with other WYSIWYG editor.
2. Drop WYSIWYG editor from Lokka repository.

I think option 2 is ideal.

**Comment by morygonzalez** [comment]
I will fix this by indroducing Quill.

https://github.com/quilljs/quill

In my environment, it works pretty nice.

**Comment by komagata** [comment]
It's nice.
